// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_task_app/test/features/task/data/repositories/task_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_task_app/core/network/network_info.dart' as _i6;
import 'package:flutter_task_app/features/task/data/datasources/task_local_data_source.dart'
    as _i5;
import 'package:flutter_task_app/features/task/data/datasources/task_remote_data_source.dart'
    as _i3;
import 'package:flutter_task_app/features/task/data/models/task_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaskModel_0 extends _i1.SmartFake implements _i2.TaskModel {
  _FakeTaskModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRemoteDataSource extends _i1.Mock
    implements _i3.TaskRemoteDataSource {
  MockTaskRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TaskModel>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<_i2.TaskModel> getTaskById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [id]),
            returnValue: _i4.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(this, Invocation.method(#getTaskById, [id])),
            ),
          )
          as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<_i2.TaskModel> addTask(_i2.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [task]),
            returnValue: _i4.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(this, Invocation.method(#addTask, [task])),
            ),
          )
          as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<_i2.TaskModel> updateTask(_i2.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i4.Future<_i2.TaskModel>.value(
              _FakeTaskModel_0(this, Invocation.method(#updateTask, [task])),
            ),
          )
          as _i4.Future<_i2.TaskModel>);

  @override
  _i4.Future<void> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [TaskLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskLocalDataSource extends _i1.Mock
    implements _i5.TaskLocalDataSource {
  MockTaskLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TaskModel>> getCachedTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTasks, []),
            returnValue: _i4.Future<List<_i2.TaskModel>>.value(
              <_i2.TaskModel>[],
            ),
          )
          as _i4.Future<List<_i2.TaskModel>>);

  @override
  _i4.Future<void> cacheTasks(List<_i2.TaskModel>? tasks) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTasks, [tasks]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
